import { GoogleGenAI, Chat } from "@google/genai";

if (!process.env.API_KEY) {
    throw new Error("API_KEY environment variable not set.");
}

const ai = new GoogleGenAI({ apiKey: process.env.API_KEY });

// Initialize a single chat instance
const chat: Chat = ai.chats.create({
  model: 'gemini-2.5-flash',
  config: {
    systemInstruction: 'You are a helpful and friendly AI assistant. Be concise and clear in your responses.',
  },
});

/**
 * Sends a message to the chat model and returns a streaming response.
 * @param message The user's message.
 * @returns An async iterator of GenerateContentResponse chunks.
 */
export const sendMessageStream = async (message: string) => {
  try {
    const result = await chat.sendMessageStream({ message });
    return result;
  } catch (error) {
    console.error("Error calling Gemini API:", error);
    if (error instanceof Error) {
        throw new Error(`API Error: ${error.message}`);
    }
    throw new Error('An unexpected error occurred while sending the message.');
  }
};

/**
 * Generates an image based on a prompt.
 * @param prompt The text prompt for image generation.
 * @returns A base64-encoded data URL of the generated image.
 */
export const generateImage = async (prompt: string) => {
    try {
        const response = await ai.models.generateImages({
            model: 'imagen-3.0-generate-002',
            prompt: prompt,
            config: {
                numberOfImages: 1,
                outputMimeType: 'image/jpeg',
                aspectRatio: '1:1',
            },
        });

        if (response.generatedImages && response.generatedImages.length > 0) {
            const base64ImageBytes = response.generatedImages[0].image.imageBytes;
            return `data:image/jpeg;base64,${base64ImageBytes}`;
        }
        throw new Error("No image was generated by the API.");
    } catch (error) {
        console.error("Error calling Gemini Image API:", error);
        if (error instanceof Error) {
            throw new Error(`Image API Error: ${error.message}`);
        }
        throw new Error('An unexpected error occurred while generating the image.');
    }
};